/* Shared stars and ranks. Edit lists/ranks.json on GitHub to customise rank boundaries. */
(function(){
const KEY="spelling-stars-total-v1";
const defaults=[{"name":"Recruit","stars":0,"icon":"🎖️"},{"name":"Private","stars":5,"icon":"🪖"},{"name":"Lance Corporal","stars":15,"icon":"🥉"},{"name":"Corporal","stars":30,"icon":"🥉"},{"name":"Sergeant","stars":50,"icon":"🥈"},{"name":"Staff Sergeant","stars":80,"icon":"🥈"},{"name":"Warrant Officer","stars":120,"icon":"🏅"},{"name":"Second Lieutenant","stars":170,"icon":"🏅"},{"name":"Lieutenant","stars":230,"icon":"🥇"},{"name":"Captain","stars":310,"icon":"🥇"},{"name":"Major","stars":410,"icon":"🌟"},{"name":"Lieutenant Colonel","stars":540,"icon":"🌟"},{"name":"Colonel","stars":700,"icon":"⭐"},{"name":"Brigadier","stars":900,"icon":"⭐⭐"},{"name":"Major General","stars":1150,"icon":"⭐⭐"},{"name":"Lieutenant General","stars":1450,"icon":"⭐⭐⭐"},{"name":"General","stars":1800,"icon":"👑"}];
let ranks=defaults;let configError=false;
function total(){try{return Math.max(0,Math.floor(Number(localStorage.getItem(KEY))||0))}catch{return 0}}
function currentRank(n){let i=0;for(let j=0;j<ranks.length;j++)if(n>=ranks[j].stars)i=j;return i}
function update(){const n=total(),i=currentRank(n),rank=ranks[i],next=ranks[i+1];document.querySelectorAll(".star-rank-card").forEach(el=>{const count=el.querySelector(".rank-stars"),name=el.querySelector(".rank-name"),progress=el.querySelector(".rank-progress"),bar=el.querySelector(".rank-bar");if(count)count.textContent=n.toLocaleString()+" stars";if(name)name.textContent=(rank.icon||"🎖️")+" "+rank.name;if(progress)progress.textContent=next?(next.stars-n)+" stars to "+next.name:"Top rank achieved!";if(bar){bar.max=next?next.stars-rank.stars:1;bar.value=next?n-rank.stars:1}let warning=el.querySelector(".rank-warning");if(configError){if(!warning){warning=document.createElement("div");warning.className="rank-warning";warning.style.cssText="color:#a02020;font-size:11px;margin-top:6px";el.append(warning)}warning.textContent="⚠️ Rank settings could not load — showing defaults"}else if(warning)warning.remove()})}
function award(n=1){if(!Number.isFinite(n)||n<=0)return;try{localStorage.setItem(KEY,String(total()+Math.floor(n)))}catch{}update()}
window.SpellingStars={award,total,update};
function init(){const style=document.createElement("style");style.textContent=`.star-rank-card{position:absolute;right:14px;top:12px;z-index:5;background:#fff;color:#30244c;border:2px solid #e5d5ff;border-radius:16px;box-shadow:0 5px 18px #21104c26;padding:11px 14px;width:190px;text-align:left;font:600 13px system-ui,sans-serif}.star-rank-card .rank-stars{font-size:18px;font-weight:900;color:#5532ad}.star-rank-card .rank-name{margin-top:3px}.star-rank-card .rank-progress{font-size:11px;color:#665a7e;margin-top:4px}.star-rank-card progress{display:block;width:100%;height:9px;margin-top:6px;accent-color:#8060e7}@media(max-width:680px){.star-rank-card{position:relative;right:auto;top:auto;margin:10px 10px 0 auto;width:190px}header{position:relative}}`;document.head.append(style);const card=document.createElement("aside");card.className="star-rank-card";card.setAttribute("aria-label","Your stars and rank");card.innerHTML='<div>⭐ <span class="rank-stars">0 stars</span></div><div class="rank-name">🎖️ Recruit</div><progress class="rank-bar" max="5" value="0"></progress><div class="rank-progress">5 stars to Private</div>';document.body.prepend(card);update();fetch("lists/ranks.json",{cache:"no-cache"}).then(r=>{if(!r.ok)throw Error("Ranks unavailable");return r.json()}).then(data=>{if(!Array.isArray(data.ranks)||!data.ranks.length)return;const valid=data.ranks.filter(r=>r&&typeof r.name==="string"&&r.name.trim()&&Number.isInteger(r.stars)&&r.stars>=0).sort((a,b)=>a.stars-b.stars);if(valid.length&&valid[0].stars===0&&valid.every((r,i)=>i===0||r.stars>valid[i-1].stars)){ranks=valid;update()}}).catch(()=>{configError=true;update()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();window.addEventListener("storage",update);
})();