/* Shared stars and ranks. Edit lists/ranks.json on GitHub to customise rank boundaries. */
(function(){
const KEY="spelling-stars-total-v1";
const defaults=[{"name":"Recruit","stars":0,"icon":"🎖️"},{"name":"Private","stars":5,"icon":"🪖"},{"name":"Lance Corporal","stars":15,"icon":"🥉"},{"name":"Corporal","stars":30,"icon":"🥉"},{"name":"Sergeant","stars":50,"icon":"🥈"},{"name":"Staff Sergeant","stars":80,"icon":"🥈"},{"name":"Warrant Officer","stars":120,"icon":"🏅"},{"name":"Second Lieutenant","stars":170,"icon":"🏅"},{"name":"Lieutenant","stars":230,"icon":"🥇"},{"name":"Captain","stars":310,"icon":"🥇"},{"name":"Major","stars":410,"icon":"🌟"},{"name":"Lieutenant Colonel","stars":540,"icon":"🌟"},{"name":"Colonel","stars":700,"icon":"⭐"},{"name":"Brigadier","stars":900,"icon":"⭐⭐"},{"name":"Major General","stars":1150,"icon":"⭐⭐"},{"name":"Lieutenant General","stars":1450,"icon":"⭐⭐⭐"},{"name":"General","stars":1800,"icon":"👑"}];
let ranks=defaults;let configError=false;
function total(){try{return Math.max(0,Math.floor(Number(localStorage.getItem(KEY))||0))}catch{return 0}}
function currentRank(n){let i=0;for(let j=0;j<ranks.length;j++)if(n>=ranks[j].stars)i=j;return i}
function update(){const n=total(),i=currentRank(n),rank=ranks[i],next=ranks[i+1];document.querySelectorAll(".star-rank-card").forEach(el=>{const count=el.querySelector(".rank-stars"),name=el.querySelector(".rank-name"),progress=el.querySelector(".rank-progress"),bar=el.querySelector(".rank-bar");if(count)count.textContent=n.toLocaleString()+" stars";if(name)name.textContent=(rank.icon||"🎖️")+" "+rank.name;if(progress)progress.textContent=next?(next.stars-n)+" stars to "+next.name:"Top rank achieved!";if(bar){bar.max=next?next.stars-rank.stars:1;bar.value=next?n-rank.stars:1}let warning=el.querySelector(".rank-warning");if(configError){if(!warning){warning=document.createElement("div");warning.className="rank-warning";warning.style.cssText="color:#a02020;font-size:11px;margin-top:6px";el.append(warning)}warning.textContent="⚠️ Rank settings could not load — showing defaults"}else if(warning)warning.remove()})}
function renderTimeline(){
 const dialog=document.getElementById("rankTimelineDialog");if(!dialog)return;
 const n=total(),idx=currentRank(n),max=ranks[ranks.length-1].stars||1;
 dialog.querySelector(".timeline-summary").textContent="⭐ "+n.toLocaleString()+" stars earned • "+ranks[idx].name;
 const track=dialog.querySelector(".rank-timeline-track");const fill=dialog.querySelector(".rank-timeline-fill");track.replaceChildren(fill);
 ranks.forEach((r,i)=>{
  const row=document.createElement("div");row.className="rank-milestone "+(i<idx?"earned":i===idx?"current":"future");
  const dot=document.createElement("span");dot.className="rank-milestone-dot";dot.textContent=i<=idx?"★":"☆";
  const info=document.createElement("div");info.className="rank-milestone-info";
  const name=document.createElement("strong");name.textContent=(r.icon||"🎖️")+" "+r.name;
  const detail=document.createElement("small");detail.textContent=i<idx?"✓ Achieved at "+r.stars.toLocaleString()+" stars":i===idx?"⭐ Current rank • "+r.stars.toLocaleString()+" stars required":(r.stars-n).toLocaleString()+" more stars needed • "+r.stars.toLocaleString()+" total";
  info.append(name,detail);row.append(dot,info);track.append(row);
 });
 const nextRank=ranks[idx+1];const fraction=nextRank?Math.min(1,(n-ranks[idx].stars)/(nextRank.stars-ranks[idx].stars)):0;const trackHeight=track.offsetHeight;const firstDot=track.children[1]?.offsetTop||0;const lastDot=track.lastElementChild?.offsetTop||trackHeight;const currentDot=track.children[idx+1]?.offsetTop||firstDot;const nextDot=track.children[idx+2]?.offsetTop||currentDot;const reached=Math.min(lastDot,currentDot+(nextDot-currentDot)*fraction);fill.style.height=Math.max(0,reached-firstDot+22)+"px";
 // Distribute decorative white stars along the earned yellow portion of the path.
 fill.replaceChildren();const count=Math.max(1,Math.min(24,Math.floor(n/Math.max(1,max/24))));
 for(let i=0;i<count;i++){const star=document.createElement("span");star.className="rank-fill-star";star.textContent="★";star.style.top=((i+.5)/count*100)+"%";fill.append(star)}
 const current=track.children[idx+1];if(current&&dialog.open)current.scrollIntoView({block:"center",behavior:"smooth"});
}
function award(n=1){if(!Number.isFinite(n)||n<=0)return;try{localStorage.setItem(KEY,String(total()+Math.floor(n)))}catch{}update();renderTimeline()}
window.SpellingStars={award,total,update};
function init(){const style=document.createElement("style");style.textContent=`.star-rank-card{position:absolute;right:14px;top:12px;z-index:5;background:#fff;color:#30244c;border:2px solid #e5d5ff;border-radius:16px;box-shadow:0 5px 18px #21104c26;padding:11px 14px;width:190px;text-align:left;font:600 13px system-ui,sans-serif}.star-rank-card .rank-stars{font-size:18px;font-weight:900;color:#5532ad}.star-rank-card .rank-name{margin-top:3px}.star-rank-card .rank-progress{font-size:11px;color:#665a7e;margin-top:4px}.star-rank-card progress{display:block;width:100%;height:9px;margin-top:6px;accent-color:#8060e7}@media(max-width:680px){.star-rank-card{position:relative;right:auto;top:auto;margin:10px 10px 0 auto;width:190px}header{position:relative}}`;document.head.append(style);
 const timelineStyle=document.createElement("style");timelineStyle.textContent=`
 .star-rank-card{cursor:pointer;transition:transform .15s,box-shadow .15s}.star-rank-card:hover{transform:translateY(-2px);box-shadow:0 8px 24px #21104c38}.star-rank-card:focus-visible{outline:3px solid #ffbd27;outline-offset:3px}
 .rank-timeline-dialog{border:0;border-radius:24px;padding:0;width:min(92vw,560px);max-height:86vh;color:#30244c;box-shadow:0 20px 70px #21104c77}.rank-timeline-dialog::backdrop{background:#221446ab;backdrop-filter:blur(4px)}
 .rank-timeline-head{position:sticky;top:0;background:#fff8df;padding:20px 22px 14px;z-index:2;border-bottom:2px solid #ffe7a1}.rank-timeline-head h2{margin:0 0 7px;font-size:1.55rem}.timeline-summary{font-weight:800;color:#6a4bb4}.rank-timeline-close{float:right;border:0;background:#6852d5;color:#fff;border-radius:10px;padding:7px 12px;font-size:1rem;cursor:pointer}
 .rank-timeline-scroll{max-height:62vh;overflow-y:auto;padding:22px 20px;background:linear-gradient(#fff,#faf7ff)}.rank-timeline-track{position:relative;margin-left:12px;padding:8px 0}
 .rank-timeline-track::before{content:"";position:absolute;top:20px;bottom:20px;left:15px;width:15px;background:#e4def0;border-radius:12px}
 .rank-timeline-fill{position:absolute;top:20px;left:15px;width:15px;background:linear-gradient(90deg,#f5b719,#ffdc49,#efb30e);border-radius:12px;z-index:1;max-height:calc(100% - 40px);overflow:hidden;transition:height .55s ease}
 .rank-fill-star{position:absolute;left:50%;transform:translate(-50%,-50%);color:#fff;font-size:12px;text-shadow:0 1px 2px #ae810c}
 .rank-milestone{position:relative;z-index:2;display:flex;gap:16px;align-items:center;min-height:78px}.rank-milestone-dot{flex:none;display:grid;place-items:center;width:45px;height:45px;border-radius:50%;background:#e9e4f1;color:#867b9d;border:3px solid white;font-size:21px}
 .rank-milestone.earned .rank-milestone-dot,.rank-milestone.current .rank-milestone-dot{background:#ffc928;color:#fff;text-shadow:0 1px 3px #9c7000}
 .rank-milestone.current .rank-milestone-info{background:#fff0ad;border:2px solid #f3bf27;border-radius:12px;padding:8px 10px}.rank-milestone-info{display:grid;gap:4px;flex:1;padding:8px 10px}.rank-milestone-info strong{font-size:1rem}.rank-milestone-info small{font-size:.79rem;color:#6d627f}.rank-milestone.future{opacity:.82}
 `;document.head.append(timelineStyle);
 const dialog=document.createElement("dialog");dialog.id="rankTimelineDialog";dialog.className="rank-timeline-dialog";dialog.setAttribute("aria-labelledby","rankTimelineTitle");dialog.innerHTML='<div class="rank-timeline-head"><button class="rank-timeline-close" type="button" aria-label="Close rank timeline">✕</button><h2 id="rankTimelineTitle">⭐ Your Rank Journey</h2><div class="timeline-summary"></div></div><div class="rank-timeline-scroll"><div class="rank-timeline-track"><div class="rank-timeline-fill"></div></div></div>';document.body.append(dialog);dialog.querySelector(".rank-timeline-close").onclick=()=>dialog.close();
 const card=document.createElement("aside");card.className="star-rank-card";card.setAttribute("aria-label","Your stars and rank");card.innerHTML='<div>⭐ <span class="rank-stars">0 stars</span></div><div class="rank-name">🎖️ Recruit</div><progress class="rank-bar" max="5" value="0"></progress><div class="rank-progress">5 stars to Private</div>';card.setAttribute("role","button");card.setAttribute("tabindex","0");card.setAttribute("aria-haspopup","dialog");card.setAttribute("title","Click to see your rank journey");card.addEventListener("click",()=>{dialog.showModal();renderTimeline()});card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();card.click()}});document.body.prepend(card);update();renderTimeline();fetch("lists/ranks.json",{cache:"no-cache"}).then(r=>{if(!r.ok)throw Error("Ranks unavailable");return r.json()}).then(data=>{if(!Array.isArray(data.ranks)||!data.ranks.length)return;const valid=data.ranks.filter(r=>r&&typeof r.name==="string"&&r.name.trim()&&Number.isInteger(r.stars)&&r.stars>=0).sort((a,b)=>a.stars-b.stars);if(valid.length&&valid[0].stars===0&&valid.every((r,i)=>i===0||r.stars>valid[i-1].stars)){ranks=valid;update();renderTimeline()}}).catch(()=>{configError=true;update()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();window.addEventListener("storage",()=>{update();renderTimeline()});
})();